[".tmux_runtime"]
    type = "archive"
    url = "https://github.com/gpakosz/.tmux/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/zsh/.antidote"]
  type = "git-repo"
  url = "https://github.com/mattmc3/antidote"
  refreshPeriod = "168h" 
